/* Lexical Parser */

!whitespace : '\t' | '\n' | '\r' | ' ' ;
!lineComment : '/' '/' { . } '\n' ;
!blockComment : '/' '*' { . | '*' } '*' '/' ;

_letter : 'A'-'Z' | 'a'-'z' | '_' ;
_digit : '0'-'9' ;
_alpha : _letter | _digit ;

/* literals */
string_literal : '"' {_alpha | ' ' | '!' | '?' | ':' | ',' | '.' }'"' ;
int : '0' | '1'-'9' {_digit} ;

/* keywords */
test : 'T' 'E' 'S' 'T' ;
given : 'G' 'I' 'V' 'E' 'N' ;
as : 'A' 'S' ;
object: 'O' 'B' 'J' 'E' 'C' 'T' ;
call : 'C' 'A' 'L' 'L' ;
then : 'T' 'H' 'E' 'N' ;
output : 'O' 'U' 'T' 'P' 'U' 'T' ;
result : 'R' 'E' 'S' 'U' 'L' 'T' ;
equals : 'E' 'Q' 'U' 'A' 'L' 'S' ;
not_equals : 'N' 'O' 'T' ' ' 'E' 'Q' 'U' 'A' 'L' 'S' ;
contains : 'C' 'O' 'N' 'T' 'A' 'I' 'N' 'S' ;

/* identifiers */
ident : _letter {_alpha} ;

/* punctuation */
lbrace : '{' ;
rbrace : '}' ;
lparen : '(' ;
rparen : ')' ;
comma : ',' ;
colon : ':' ;
semicolon : ';' ;
dot : '.' ;

/* Syntactic Parser */

<<
import (
    "github.com/Siposattila/TestMe/tmtsl/ast"
)
>>

Configuration
    : TestDefinitions GlobalDefinitions << ast.NewConfiguration($0, $1) >>
    ;

TestDefinitions
    : TestDefinitions TestDefinition << ast.AppendTestDefinition($0, $1) >>
    | empty << ast.NewTestDefinitionList() >>
    ;

GlobalDefinitions
    : GlobalDefinitions GlobalDefinition << ast.AppendGlobalDefinition($0, $1) >>
    | empty << ast.NewGlobalDefinitionList() >>
    ;

GlobalDefinition
    : Expression semicolon << ast.NewGlobalDefinition($0) >>
    ;

TestDefinition
    : test string_literal GivenBlock CallBlock ThenBlock semicolon << ast.NewTestDefinition($1, $2, $3, $4) >>
    ;

GivenBlock
    : given GivenExpressions << ast.NewGivenBlock($1) >>
    | empty << ast.NewGivenBlock(nil) >>
    ;

GivenExpressions
    : GivenExpressions comma Expression << ast.AppendGivenExpression($0, $2) >>
    | Expression << ast.NewGivenExpressionList($0) >>
    | empty << ast.NewGivenExpressionList(nil) >>
    ;

Object
    : object ident lbrace ObjectProperties rbrace << ast.NewObject($1, $3) >>
    ;

ObjectProperties
    : ObjectProperties comma ObjectProperty << ast.AppendObjectProperty($0, $2) >>
    | ObjectProperty << ast.NewObjectPropertyList($0) >>
    | empty << ast.NewObjectPropertyList(nil) >>
    ;

ObjectProperty
    : string_literal colon string_literal << ast.NewObjectPropertyStringLiteral($0, $2) >>
    | string_literal colon int << ast.NewObjectPropertyIntegerLiteral($0, $2) >>
    ;

CallBlock
    : call ident lparen Arguments rparen << ast.NewCallBlock($1, $3) >>
    ;

Arguments
    : Arguments comma Expression << ast.AppendArgument($0, $2) >>
    | Expression << ast.NewArgumentList($0) >>
    | empty << ast.NewArgumentList(nil) >>
    ;

ThenBlock
    : then Expression << ast.NewThenBlock($1) >>
    ;

Expression
    : string_literal << ast.NewStringLiteral($0) >>
    | int << ast.NewIntegerLiteral($0) >>
    | ident << ast.NewIdentifier($0) >>
    | Expression as ident << ast.NewDefinitionExpression($0, $2) >>
    | Object as ident << ast.NewDefinitionExpression($0, $2) >>
    | TestOperation Operation string_literal << ast.NewTestOperationExpressionStringLiteral($0, $1, $2) >>
    | TestOperation Operation int << ast.NewTestOperationExpressionIntegerLiteral($0, $1, $2) >>
    | TestOperation Operation ident << ast.NewTestOperationExpressionIdentifier($0, $1, $2) >>
    ;

TestOperation
    : output
    | result
    | ident dot ident
    ;

Operation
    : equals
    | not_equals
    | contains
    ;
