/* Lexical Parser */

!whitespace : '\t' | '\n' | '\r' | ' ' ;
!lineComment : '/' '/' { . } '\n' ;
!blockComment : '/' '*' { . | '*' } '*' '/' ;

_letter : 'A'-'Z' | 'a'-'z' | '_' ;
_digit : '0'-'9' ;
_alpha : _letter | _digit ;

/* literals */
string_literal : '"' {_alpha | ' ' | '!' | '?' | ':' | ',' | '.' }'"' ;
int : '0' | '1'-'9' {_digit} ;

/* keywords */
test : 'T' 'E' 'S' 'T' ;
given : 'G' 'I' 'V' 'E' 'N' ;
as : 'A' 'S' ;
object: 'O' 'B' 'J' 'E' 'C' 'T' ;
call : 'C' 'A' 'L' 'L' ;
then : 'T' 'H' 'E' 'N' ;
output : 'O' 'U' 'T' 'P' 'U' 'T' ;
result : 'R' 'E' 'S' 'U' 'L' 'T' ;
equals : 'E' 'Q' 'U' 'A' 'L' 'S' ;
not_equals : 'N' 'O' 'T' 'E' 'Q' 'U' 'A' 'L' 'S' ;
contains : 'C' 'O' 'N' 'T' 'A' 'I' 'N' 'S' ;

/* punctuation */
lbrace : '{' ;
rbrace : '}' ;
lparen : '(' ;
rparen : ')' ;
comma : ',' ;
colon : ':' ;
semicolon : ';' ;
dot : '.' ;

/* Syntactic Parser */

<<
import (
    "github.com/Siposattila/TestMe/tmtsl/ast"
)
>>

Configuration
    : GlobalDefinitions TestDefinitions << ast.NewConfiguration($1, $0) >>
    ;

TestDefinitions
    : TestDefinitions TestDefinition << ast.AppendDefinition($0, $1) >>
    | empty << ast.NewDefinitionList() >>
    ;

GlobalDefinitions
    : GlobalDefinitions GlobalDefinition << ast.AppendDefinition($0, $1) >>
    | empty << ast.NewDefinitionList() >>
    ;

GlobalDefinition
    : DefinitionExpression semicolon << ast.NewGlobalDefinition($0) >>
    ;

TestDefinition
    : test string_literal GivenBlock CallBlock ThenBlock semicolon << ast.NewTestDefinition($1, $2, $3, $4) >>
    ;

GivenBlock
    : given GivenExpressions << ast.NewGivenBlock($1) >>
    | empty << ast.NewGivenBlock(nil) >>
    ;

GivenExpressions
    : GivenExpressions comma DefinitionExpression << ast.AppendGivenExpression($0, $2) >>
    | DefinitionExpression << ast.NewGivenExpressionList($0) >>
    | empty << ast.NewGivenExpressionList(nil) >>
    ;

Object
    : object string_literal lbrace ObjectProperties rbrace << ast.NewObject($1, $3) >>
    ;

ObjectProperties
    : ObjectProperties comma ObjectProperty << ast.AppendObjectProperty($0, $2) >>
    | ObjectProperty << ast.NewObjectPropertyList($0) >>
    | empty << ast.NewObjectPropertyList(nil) >>
    ;

ObjectProperty
    : string_literal colon string_literal << ast.NewObjectPropertyStringLiteral($0, $2) >>
    | string_literal colon int << ast.NewObjectPropertyIntegerLiteral($0, $2) >>
    ;

CallBlock
    : call string_literal lparen Arguments rparen << ast.NewCallBlock($1, $3) >>
    ;

Arguments
    : Arguments comma Literal << ast.AppendArgument($0, $2) >>
    | Literal << ast.NewArgumentList($0) >>
    | empty << ast.NewArgumentList(nil) >>
    ;

ThenBlock
    : then TestOperationExpression << ast.NewThenBlock($1) >>
    ;

Literal
    : string_literal << ast.NewStringLiteral($0) >>
    | int << ast.NewIntegerLiteral($0) >>
    ;

DefinitionExpression
    : Literal as Literal << ast.NewDefinitionExpression($0, $2) >>
    | Object as Literal << ast.NewDefinitionExpression($0, $2) >>
    ;

TestOperationExpression
    : TestOperation Operation string_literal << ast.NewTestOperationExpressionStringLiteral($0, $1, $2) >>
    | TestOperation Operation int << ast.NewTestOperationExpressionIntegerLiteral($0, $1, $2) >>
    ;

TestOperation
    : output
    | result
    | string_literal dot string_literal
    ;

Operation
    : equals
    | not_equals
    | contains
    ;
